version: '3.8'
services:
  instagram-clone-backend:
    container_name: instagram-clone-backend
    image: instagram-clone-backend:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
